name = "lean-playground"
version = "0.1.0"
defaultTargets = ["lean-playground"]

[[lean_lib]]
name = "LeanPlayground"

[[lean_exe]]
name = "lean-playground"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.18.0"